val LANG: MutableMap<String, String> = mutableMapOf(
    "start_command" to "Hi",
    "help_command" to "[查看帮助🔍](https://littlemengbot.github.io/1953/06/15/index/)",
    "dream_command" to "小萌萌的梦想，就是赚好多好多钱买大大大大大的房子，每日三餐都加上好吃的肉肉，" +
            "和我的主人走遍世界的每一个角落，啊......如果可以的话。💤💤💤",
    "toutou_no_reply" to "不透人只能被透哦",
    "toutou_self" to "👋🐛大师 <a href=\"tg://user?id=%s\">%s</a> 刚刚自己透了自己！",
    "toutou_with" to "<a href=\"tg://user?id=%s\">%s</a> 透了 <a href=\"tg://user?id=%s\">%s</a> ！",
    "tietie_no_reply" to "没有想贴的对象吗？那就和小萌萌贴贴吧！",
    "tietie_self" to "<a href=\"tg://user?id=%s\">%s</a> 自己和自己贴贴，好可怜啊！",
    "tietie_with" to "<a href=\"tg://user?id=%s\">%s</a> 和 <a href=\"tg://user?id=%s\">%s</a> 贴贴！",
    "zouzou_no_reply" to "搁这儿打空👊呢？",
    "zouzou_self" to "<a href=\"tg://user?id=%s\">%s</a> 自己揍了自己一顿。",
    "zouzou_with" to "<a href=\"tg://user?id=%s\">%s</a> 狠狠揍了 <a href=\"tg://user?id=%s\">%s</a> 一顿",
    "momo_no_reply" to "摸萌萌，摸萌萌！",
    "momo_self" to "<a href=\"tg://user?id=%s\">%s</a> 自己摸了摸自己。",
    "momo_with" to "<a href=\"tg://user?id=%s\">%s</a> 摸了摸 <a href=\"tg://user?id=%s\">%s</a> 的%s，" +
            "<a href=\"tg://user?id=%s\">%s</a> %s",
    "delete_button" to "删除",
    "usa" to "你说的都对，但是据美国约翰斯·霍普金斯大学统计数据显示，截至美国东部时间%s日%s时%s分，" +
            "美国累计新冠肺炎确诊病例超过%s万例，达%s万例，累计死亡病例超过%s万例，达%s万例。过去24小时，美国新增确诊病例%s例，新增死亡病例%s例。",
    "india" to "你说的都对，但是据印度卫生部统计数据显示，截至印度时间%s日%s时%s分，" +
            "印度累计新冠肺炎确诊病例超过%s万例，达%s万例，累计死亡病例超过%s万例，达%s万例。过去24小时，印度新增确诊病例%s例，新增死亡病例%s例。",
    "getting" to "正在获取...",
    "sending" to "正在发送...",
    "processing" to "正在处理...",
    "finding" to "正在查找...",
    "find_empty" to "找不到哦...",
    "process_error" to "处理失败了。。。",
    "converting" to "正在转换格式...",
    "convert_failed" to "转换失败...",
    "lock_true" to "已在处理，请稍后。（此消息五秒后自毁。）",
    "no_sticker" to "请回复一张贴纸哦～",
    "no_gif" to "请回复一张Gif哦～\n\n（温馨提示：动态贴纸请使用/gs命令下载。）",
    "gif_hint" to "telegram不资瓷以文件类型发送gif，请自行将后缀更改为.gif",
    "permission_failed" to "您无权执行此操作。",
    "send_success" to "发送成功！",
    "send_failed" to "发送失败了。。。",
    "remake_congratulation" to "恭喜🎉，你重開到了%s！",
    "remake_nEurope" to "恭喜🎉！你重開到了北歐的%s！",
    "remake_sad" to "很不幸，你重開到了%s，好可憐吶！萌萌抱抱你(＞人＜;)",
    "remake_japan" to "恭喜🎉！你重開到了家鄉大日本，sakura永遠為你盛開！",
    "remake_Netherlands" to "恭喜🎉！你重開到了荷蘭🇳🇱🇳🇱🇳🇱，中嘞撈翔！",
    "remake" to "你重開到了%s",
    "wiki_empty" to "请在命令后面加上要查找的关键词。",
    "wiki_result_parse" to "<a href=\"%s\">%s🔍</a>",
    "lunar_data_fmt" to "<b>今天是%s年%s月%s日，\n%s年（%s）    %s月%s</b>\n\n" +
            "<b>彭祖百忌：</b><code>%s</code>\n\n<b>今日宜：</b><code>%s</code>\n\n" +
            "<b>今日忌：</b><code>%s</code>\n\n<b>今日八字：</b><code>%s</code>\n\n<b>吉神方位：</b><code>%s</code>\n\n",
    "xi_empty" to "请在命令后加上要生成的内容或回复一则带有文本的消息。",
    "xi_too_long" to "文本过长。限制：500字。",
    "file_base_url" to "https://api.telegram.org/file/bot%s/%s",
    "image_search_single" to "[%s🔍](%s)\n\n",
    "image_search_foot" to "搜索来源：谷歌\n由小萌萌强力驱动！",
    "image_not_found" to "小萌萌没有从咕咕噜找到哦。。。",
    "image_reply" to "请回复一张图片哦～",
    "constellation_fmt" to "----*今天是%s*-----\n\n*%s运势如下：*\n\n" +
            "*综合运势：*%s\n%s\n\n" +
            "*爱情运势：*%s\n%s\n\n" +
            "*事业学业：*%s\n%s\n\n" +
            "*财富运势：*%s\n%s\n\n" +
            "*健康：*%s\n\n_数据来源：星座屋_",
    "constellation_hint" to "请在命令后加上正确星座，如：白羊座、金牛座、双子座、巨蟹座、狮子座、处女座、" +
            "天秤座、天蝎座、人马座、摩羯座、水瓶座、双鱼座。（支持简繁体）",
    "shot_reply_hint" to "请回复一条http/https开头的纯链接消息。",
    "shot_args_error" to "指定的长或宽错误，最小值为500，最大为20000。",
    "shot_url_error" to "链接有误，请回复一条http/https开头的纯链接消息。",
    "shot_in" to "正在截图...(时间与网页内容复杂度有关，不是卡住，请稍等)",
    "shot_error" to "出错！",
    "music_button_hint" to "前往YouTube观看",
    "music_args_empty" to "请在命令后加上音乐名。",
    "no_video_link" to "请回复或者在命令后加一个视频链接。",
    "video_downloading" to "正在下载视频，请稍后...（使用Tor网络，因此速度很慢。）",
    "video_download_failed" to "下载失败了！可能的原因：视频大于20M；地址有误。",
    "qr_head" to "*解析结果：*`%s`",
    "qr_not_found" to "萌萌没有在这张图片中找到二维码哦。",
    "qr_caption" to "Generated By @XiaoMengMengBot",
    "qr_generate_error" to "生成错误！",
    "qr_hint" to "请在命令后加上要生成的文本以生成对应二维码，或者回复一张含有二维码的图片以进行解析。",
    "replace_args_error" to "错误！",
    "coin_empty" to "请在命令后加上所要查询的币种缩写，例如：BTC，xmr"
)

val momo_seed_text = listOf(
    "发出了愉悦的叫声😆。", "叫了出来：嗯，啊！", "嘴里喊着，不要～不要～", "似乎有些生气了！气不气气不气？（叉腰）",
    "似乎没有注意到惹。", "正在玩📱，丝毫没有感觉。", "摸了回去。", "露出了一丝不易察觉的娇羞💖。", "狠狠地摸了回去。",
    "心里似乎想着：多摸几次，多摸几次！", "掏出了自己的🌸为手机大喊：爱慕拆腻子！", "居然掏出了自己的**！",
    "好像很难过啊。不哭不哭❤️！", "反手摸了摸小萌萌。萌萌好开心啊！", "报警了🚔！", "居然宽掉了自己的衣服！",
    "反👋出道了这个大流氓。", "和他一起唱起了《🌸为美》", "打电话向自己的大表哥习**告状！", "居然在公共场合拉起了臭臭！💩"
)

val momo_seed_letter = listOf(
    "jiojio", "腿子", "奶子", "🐻", "秃头", "头", "胳膊", "肥肘子", "小脸蛋儿", "小圆屁股", "额头",
    "老婆", "🐮子", "大腿", "脖子", "🐷🐷脑袋", "胳肢窝", "肱三头肌", "🐻大肌", "软软的手手"
)